repo_url: https://github.com/flanksaul/mkdocs-netlify-starter
site_dir: "../dist"
repo_name: knowledge base
docs_dir: ./
site_name: Knowledge Base
theme:
  name: "material"
  palette:
    primary: "royalblue"
  logo: "img/favicon.png"
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  - codehilite:
      linenums: true
  - toc:
      permalink: true
plugins:
  - search
  - autolinks
  - macros:
      j2_block_start_string: "[[%"
      j2_block_end_string: "%]]"
      j2_variable_start_string: "%%{"
      j2_variable_end_string: "}%%"
  - same-dir
extra_css:
  - overrides/style.css