name: Create Release
on:
  workflow_dispatch: {}
jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.12.0
    steps:
      - uses: actions/checkout@v2
      - run: make deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
